import tracery

# format: Chomsky's famous quote, "Colorless green ideas sleep furiously"
# This sentence is used by Chomsky to illustrate how a sentence is grammatically correct but makes no sense.
# Similarly, the sentences that will be generated by this generator are grammatically correct but make no understanable meanning.

# ChatGPT is used only to generate the below vocabularies: https://chatgpt.com/share/691614c0-52a4-800b-a0f5-acfa1e3fa8e7

adjective = [
    "bright", "dark", "pale", "vivid", "muted", "dull", "light", "deep", "soft", "intense", "faded",
    "rich", "washed-out", "glowing", "shadowy", "neutral", "saturated", "subdued", "radiant", "bleak",
    "vibrant", "dim", "brilliant", "flat", "lustrous", "gloomy", "sparkling", "opaque", "translucent", "glossy", "matte"
]
color = [
    "indigo", "turquoise", "teal", "magenta", "maroon", "beige", "cream", "gold", "silver", "bronze", "amber", "crimson",
    "scarlet", "emerald", "jade", "ivory", "charcoal", "navy", "coral", "peach", "lavender", "mint", "cyan"
]
abstract_noun = [
    "freedom", "love", "happiness", "anger", "justice", "knowledge", "truth", "beauty", "fear", "hope", "peace", "power", "wisdom",
    "faith", "honesty", "courage", "loyalty", "friendship", "trust", "patience", "pride", "sadness", "curiosity", "kindness",
    "strength", "jealousy", "desire", "compassion", "inspiration", "creativity", "faithfulness", "ambition", "determination",
    "failure", "success", "hatred", "guilt", "shame", "glory", "memory"
]
verb_3rd_sing = [
    "arrives", "sleeps", "smiles", "laughs", "cries", "falls", "sits",
    "stands", "comes", "goes", "stays", "happens", "appears", "exists",
    "works", "waits", "runs", "jumps", "swims", "flies", "walks",
    "travels", "lies", "rests", "changes", "grows", "shines", "lives",
    "sneezes", "coughs", "dances", "talks", "listens", "arrives", "returns",
    "remains", "ends", "begins", "starts", "occurs"
]
adverb = [
    "quickly", "slowly", "carefully", "easily", "quietly", "loudly", "happily", "sadly", "angrily", "bravely", "politely", "honestly",
    "gracefully", "seriously", "gently", "roughly", "eagerly", "suddenly", "eventually", "always", "never", "often", "rarely", "sometimes",
    "soon", "later", "now", "then", "here", "there", "everywhere"
]


rules = {
    "origin": "#adjective# #color# #abstract_noun# #verb# #adverb#",
    "adjective": adjective,
    "color": color,
    "abstract_noun": abstract_noun,
    "verb": verb_3rd_sing,
    "adverb": adverb
}

grammar = tracery.Grammar(rules)
for i in range(10):
    print(grammar.flatten("#origin#"))

# bonus

# format: a dialogue Plato's the Symposium https://www.gutenberg.org/files/1600/1600-h/1600-h.htm
# Socrates: Then would you still say that love is beautiful?
# Agathon replied: I fear that I did not understand what I was saying.
# Socrates: You made a very good speech, Agathon, replied Socrates;
#           but there is yet one small question which I would fain ask:—Is not the good also the beautiful?

abstract_noun = [
    "freedom", "love", "happiness", "anger", "justice", "knowledge", "truth", "beauty", "fear", "hope", "peace", "power", "wisdom",
    "faith", "honesty", "courage", "loyalty", "friendship", "trust", "patience", "pride", "sadness", "curiosity", "kindness",
    "strength", "jealousy", "desire", "compassion", "inspiration", "creativity", "faithfulness", "ambition", "determination",
    "failure", "success", "hatred", "guilt", "shame", "glory", "memory"
]

adjective = [
    "bright", "dark", "pale", "vivid", "muted", "dull", "light", "deep", "soft", "intense", "faded",
    "rich", "washed-out", "glowing", "shadowy", "neutral", "saturated", "subdued", "radiant", "bleak",
    "vibrant", "dim", "brilliant", "flat", "lustrous", "gloomy", "sparkling", "opaque", "translucent", "glossy", "matte"
]

script = {
    "dialogue": "#line1#\n#line2#\n#line3#",
    "line1": "Socrates: Would you still say that #concept# is[adj:#adjective#] #adj#?",
    "concept": abstract_noun,
    "adjective": adjective,
    "line2": "Agathon replied: I fear that I did not understand what I was saying",
    "line3": "Socrates: Is not the #adjective# also the #adj#?"
}

new_grammar = tracery.Grammar(script)
for i in range(1):
    print(new_grammar.flatten("#dialogue#"))

print("-----")

# bonus

# format: a conversation between two philosophers in Zhuangzhi's The Floods of Autumn
# Zhuangzi and Huizi were walking on the dam over the Hao
# the former said, 'These thryssas come out, and play about at their ease - that is the enjoyment of fishes.'
# The other said, 'You are not a fish; how do you know what constitutes the enjoyment of fishes?'
# Zhuangzi rejoined, 'You are not I. How do you know that I do not know what constitutes the enjoyment of fishes?'
# Huizi said, 'I am not you; and though indeed I do not fully know you, you certainly are not a fish,
#            and (the argument) is complete against your knowing what constitutes the happiness of fishes.'
# Zhuangzi replied, 'Let us keep to your original question. You said to me, "How do you know what constitutes the enjoyment of fishes?"
#            You knew that I knew it, and yet you put your question to me - well, I know it (from our enjoying ourselves together) over the Hao.'

animal = [
    "dog", "cat", "lion", "tiger", "elephant", "giraffe", "zebra", "monkey",
    "bear", "wolf", "fox", "rabbit", "deer", "horse", "cow", "sheep",
    "goat", "pig", "chicken", "duck", "goose", "turkey", "owl", "eagle",
    "hawk", "parrot", "sparrow", "dolphin", "whale", "shark", "octopus",
    "crab", "lobster", "frog", "turtle", "snake", "lizard", "ant", "bee",
    "butterfly", "spider", "rat", "mouse", "kangaroo", "koala", "panda",
    "camel", "hippopotamus", "rhinoceros"
]

verb_phrase = [
    "wake up", "sit down", "stand up", "get up", "fall apart", "break down",
    "come back", "go out", "show up", "give in", "run away", "turn up",
    "turn back", "go back", "check in", "check out", "grow up", "lie down",
    "move in", "move out", "pass away", "look around", "look after", "look out",
    "hang out", "break out", "take off", "take place", "set in", "show off",
    "catch up", "slow down", "speed up", "calm down", "wake up", "back off"
]

verb_action = [
    "run", "jump", "hop", "crawl", "swim", "fly", "climb", "slink", "slither",
    "pounce", "leap", "sprint", "soar", "glide", "scurry", "burrow", "waddle",
    "creep", "stalk", "swoop", "flutter", "perch", "nest", "roam", "graze",
    "forage", "hunt", "howl", "bark", "meow", "chirp", "squeak", "growl",
    "hiss", "whistle", "hoot", "buzz", "caw", "snarl", "sniff", "scratch",
    "paw", "scratch", "shake", "wiggle", "flap", "gallop", "trot", "nap",
    "sleep", "doze", "yawn", "stretch", "roll", "dig", "scratch around",
    "chase away", "scuttle off", "scamper away", "hop about", "flutter by"
]

verb_gerund = [
    "running", "jumping", "sleeping", "sitting", "standing", "walking",
    "swimming", "flying", "crawling", "hopping", "slinking", "slithering",
    "pouncing", "leaping", "sprinting", "soaring", "gliding", "scurrying",
    "burrowing", "waddling", "creeping", "stalking", "swooping", "fluttering",
    "perching", "nesting", "roaming", "grazing", "foraging", "hunting",
    "howling", "barking", "meowing", "chirping", "squeaking", "growling",
    "hissing", "hooting", "buzzing", "cawing", "snarling", "sniffing",
    "scratching", "pawing", "shaking", "wiggling", "flapping", "galloping",
    "trotting", "napping", "dozing", "yawning", "stretching", "rolling",
    "digging", "chasing away", "scuttling off", "scampering away", "hoping about",
    "fluttering by"
]

abstract_noun = [
    "freedom", "love", "happiness", "anger", "justice", "knowledge", "truth", "beauty", "fear", "hope", "peace", "power", "wisdom",
    "faith", "honesty", "courage", "loyalty", "friendship", "trust", "patience", "pride", "sadness", "curiosity", "kindness",
    "strength", "jealousy", "desire", "compassion", "inspiration", "creativity", "faithfulness", "ambition", "determination",
    "failure", "success", "hatred", "guilt", "shame", "glory", "memory"
]

verb_know = [
    "understand", "comprehend", "grasp", "perceive", "discern", "recognize",
    "realize", "apprehend", "acknowledge", "cognize", "be aware", "be conscious",
    "fathom", "conceive", "distinguish", "detect", "notice", "identify",
    "learn", "memorize", "recall", "remember", "envision", "interpret",
    "appreciate", "assess", "evaluate", "estimate", "judge", "conclude",
    "verify", "confirm", "ascertain", "observe", "discover", "speculate",
    "infer", "suppose", "believe", "underpin", "validate", "authenticate"
]


conversation = {
    "dialogue": "#intro#\n#line1#\n#line2#\n#line3#\n#line4#\n#line5#",
    "intro": "Zhuangzi and Huizi were #gerund# on the dam over the Hao.",
    "gerund": verb_gerund,
    "line1": "Zhuangzi: These [being:#animal#]#being.s# #verb_action# and #verb_phrase# - that is the [abstract:#abstract_noun#]#abstract# of #being.s#.",
    "animal": animal,
    "verb_action": verb_action,
    "verb_phrase": verb_phrase,
    "abstract_noun": abstract_noun,
    "line2": "Huizi: You are not #being.a#; how do you [epistemic:#verb_know#]#epistemic# what constitutes the #abstract# of #being.s#?",
    "verb_know": verb_know,
    "line3": "Zhuangzi: You are not I. How do you #epistemic# that I do not #epistemic# what constitutes the #abstract# of #being.s#?",
    "line4": "Huizi: I am not you; and though indeed I do not fully #epistemic# you, you certainly are not #being.a#, and  the argument is complete against your #epistemic#ing what constitutes the #abstract# of #being.s#.",
    "line5": "Zhuangzi: Let us keep to your original question. You said to me, 'How do you #epistemic# what constitutes the #abstract# of #being.s#?' You #epistemic.ed# that I #epistemic.ed# it, and yet you put your question to me - well, I #epistemic# it from our #abstract# together over the Hao."
}

from tracery.modifiers import base_english

story_grammar = tracery.Grammar(conversation)
story_grammar.add_modifiers(base_english)
for i in range(1):
    print(story_grammar.flatten("#dialogue#"))